# Generated by Django 4.2.7 on 2023-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('href', models.CharField(max_length=36)),
                ('avatar', models.CharField(max_length=134)),
                ('name', models.CharField(max_length=24)),
                ('owner', models.CharField(max_length=6)),
                ('desc', models.CharField(max_length=12)),
                ('call_no', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('updated_at', models.CharField(max_length=48)),
                ('created_at', models.CharField(max_length=48)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
