# Generated by Django 4.2.7 on 2023-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
